### ISSUE TITLE
请问这个是必选在elementUi下才能使用的吗

### ISSUE THREAD

**Issue by wangbinze** [hql7/wl-vue-select#8]

**Comment by hql7** [comment]
都是基于elementui的，按需引入即可



在 2020-06-28 10:33:15，"Agoni" <notifications@github.com> 写道：

**Comment by wangbinze** [comment]
> 都是基于elementui的，按需引入即可 在 2020-06-28 10:33:15，"Agoni" <notifications@github.com> 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wangbinze** [comment]
额  我用的vuetifyjs  但是也需要这么一个功能

**Comment by hql7** [comment]
一个项目里使用多种插件还是挺正常的，一个ui库涵盖不了



在 2020-06-28 15:00:46，"Agoni" <notifications@github.com> 写道：

额 我用的vuetifyjs 但是也需要这么一个功能

**Comment by wangbinze** [comment]
> 一个项目里使用多种插件还是挺正常的，一个ui库涵盖不了在2020-06-28 15:00:46，“ Agoni” <notifications@github.com>填充：额我用的vuetifyjs但是也需要这么一个功能-之所以收到此评论，是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。

但是再引elementui进来其实有点不太显示了，会导致一些冲突

**Comment by hql7** [comment]
按需引入即可，只用到el的select，tree，tag，如果我把用到的element-ui集成进来，你是不是就能接受了，，，其实很多插件都是这样



在 2020-06-28 15:09:00，"Agoni" <notifications@github.com> 写道：

一个项目里使用多种插件还是挺正常的，一个ui库涵盖不了在2020-06-28 15:00:46，“ Agoni” notifications@github.com填充：额我用的vuetifyjs但是也需要这么一个功能-之所以收到此评论，是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。

但是再引elementui进来其实有点不太显示了，会导致一些冲突

**Comment by wangbinze** [comment]
> 按需约会即可，只用到el的选择，tree，tag，如果我把用到的element-ui集成进来，你是不是就能接受了，，，其实很多插件都是这样在2020-06- 28 15:09:00，“ Agoni” <notifications@github.com>替换为：一个项目里使用多种插件还是挺正常的，一个ui库涵盖不了在2020-06-28 15:00:46，” Agoni” notifications@github.com填充：额我用的vuetifyjs但是也需要这么一个功能-之所以收到此评论。是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。但是再引elementui进来其实有点不太显示了，会导致一些冲突-您收到此评论是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。

嗯嗯 好多  待会我试一下  我开始相成了要把整个ui框架引入
